FROM node:20-alpine AS base

WORKDIR /app  

COPY ./hooks/package*.json ./  

COPY ./hooks/tsconfig.json .
RUN npm install  

COPY ./hooks/prisma prisma
RUN npx prisma generate
 
COPY ./hooks/src src

RUN npm run build

EXPOSE 3002

CMD ["node", "dist/index.js"]  
