FROM node:20-alpine AS base

WORKDIR /app  

COPY ./processor/package*.json ./  

COPY ./processor/tsconfig.json .
RUN npm install  

COPY ./processor/prisma prisma
RUN npx prisma generate
 
COPY ./processor/src src

RUN npm run build

CMD ["node", "dist/index.js"]
