FROM node:20-alpine AS base

WORKDIR /app  

COPY ./worker/package*.json ./

COPY ./worker/tsconfig.json .
RUN npm install  

COPY ./worker/prisma prisma
RUN npx prisma generate
 
COPY ./worker/src src

RUN npm run build

CMD ["node", "dist/index.js"]
