apiVersion: v1
kind: ConfigMap
metadata:
  name: zapier-frontend-config
  namespace: frontend-team
data:
  NEXT_PUBLIC_BACKEND_URL: ""
  NEXT_PUBLIC_HOOKS_URL: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zapier-frontendPod
  namespace: frontend-team
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zapier-frontend
  template:
    metadata:
      labels:
        app: zapier-frontend
    spec:
      containers:
        - name: zapier-frontend
          image: dockbh/zapier-frontend:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: zapier-frontend-config
              mountPath: "/app/secrets"
              readOnly: true
      volumes:
        - name: zapier-frontend-config
          configMap:
            name: zapier-frontend-config
---
apiVersion: v1
kind: Service
metadata:
  name: zapier-frontService
  namespace: frontend-team
spec:
  selector:
    app: zapier-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP