# name: CD

# on:
#   workflow_run:
#     workflows: ["CI"]
#     types:
#       - success

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Deploy to EC2 via SSH
#         uses: appleboy/ssh-action@v0.1.6
#         with:
#           host: ${{ secrets.EC2_HOST }}
#           username: ${{ secrets.EC2_USER }}
#           key: ${{ secrets.EC2_SSH_KEY }}
#           script: |
#           docker pull dockbh/zapier-worker:${{github.sha}}
#           docker pull dockbh/zapier-processor:${{github.sha}}
#           docker pull dockbh/zapier-backend:${{github.sha}}
#           docker pull dockbh/zapier-frontend:${{github.sha}}  
#           docker pull dockbh/zapier-hooks:${{github.sha}}

          