name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker login 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/zapier-frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/zapier-backend:latest

      - name: Build and push hooks
        uses: docker/build-push-action@v2
        with:
          context: ./hooks
          file: ./hooks/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/zapier-hooks:latest

      - name: Build and push processor
        uses: docker/build-push-action@v2
        with:
          context: ./processor
          file: ./processor/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/zapier-processor:latest  

      - name: Build and push worker
        uses: docker/build-push-action@v2
        with:
          context: ./worker
          file: ./worker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/zapier-worker:latest