name: CI_CD_Frontend

on:
  push:
    branches: [master]
    paths:
      - './frontend/**'
      - '.github/workflows/ci_cd_frontend.yml'
    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker login 
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/zapier-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/zapier-frontend:${{ github.sha }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull dockbh/zapier-frontend:${{ github.sha }}
            docker stop dockbh/zapier-frontend || true
            docker rm dockbh/zapier-frontend || true
            docker run -d \
              --name fe \
              --network app-network \
              --restart always \
              -p 3000:3000 \              
              dockbh/zapier-frontend:${{ github.sha }}  
      