apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-reverse-proxy-config
  namespace: default
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }

    http {
      server {
        listen 80;
        server_name k8s.zapierBe.com

        # Proxy /api requests to backend service
        location / {
          proxy_pass http://backend.backend-team.svc.cluster.local:3001/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }

      server {
        listen 80;
        server_name k8s.zapierFe.com

        # Proxy /api requests to backend service
        location / {
          proxy_pass http://frontend.frontend-team.svc.cluster.local:3000/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection 'upgrade';
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }
    }

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
spec:
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
        - name: nginx-reverse-proxy
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-reverse-proxy-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-reverse-proxy-config
          configMap:
            name: nginx-reverse-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
spec:
  selector:
    app: nginx-reverse-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer